### PR TITLE
Fix the `encoding` option

### LINKED ISSUE #7: Encoding is not being passed to write-file-atomic correctly
The writeFileAtomic.sync method (required from the write-file-atomic package) accepts the encoding when passed as the encoding property of options, not as a string. Therefore, this package is not actually writing the cache file with the requested encoding.

See https://github.com/npm/write-file-atomic/blob/1597785cb9e1152056d905a357b3891b3295506d/index.js#L184

### PR DESCRIPTION
**Pull request by mojavelinux**
Fixes #7

### CODE REVIEW

**Comment by jamestalmage** [comment]
You've got some lint errors

**Comment by mojavelinux** [comment]
Doh! I swear I checked, but I looks like I made changes after that. I'll fix asap!

**Comment by mojavelinux** [comment]
Fixed. Though it appears that CI is not working on master, so it's likely this PR is going to fail to. But I'm confident that the problems aren't being introduced by this change.

**Comment by mojavelinux** [comment]
The tests pass to the degree they pass in master. The new test is passing.

Do we have to get master working before this is merged?

**Comment by mojavelinux** [comment]
Is this good now?

**Comment by mojavelinux** [comment]
Is there anything I can do to move this along?

**Comment by sindresorhus** [comment]
Travis is failing: https://travis-ci.org/avajs/caching-transform/jobs/327081930

**Comment by mojavelinux** [comment]
Which brings me back to my question:

> Do we have to get master working before this is merged?

Master is broken. Am I expected to fix master too?

**Comment by mojavelinux** [comment]
Thanks @sindresorhus!

**Pull request merged**
